# Generated by Django 6.0.2 on 2026-02-12 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('software_type', models.CharField(choices=[('AI', 'AI Tool'), ('Software', 'General Software')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('available', 'ว่าง'), ('in_use', 'ใช้งานอยู่'), ('reserved', 'จองแล้ว'), ('maintenance', 'แจ้งซ่อม')], default='available', max_length=20)),
                ('pc_type', models.CharField(default='General', max_length=20)),
                ('current_user', models.CharField(blank=True, max_length=100, null=True)),
                ('session_start', models.DateTimeField(blank=True, null=True)),
                ('installed_software', models.ManyToManyField(blank=True, to='lab_management.software')),
            ],
        ),
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(auto_now_add=True)),
                ('satisfaction_score', models.IntegerField(blank=True, null=True)),
                ('computer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab_management.computer')),
            ],
        ),
    ]
