# Generated by Django 6.0.2 on 2026-02-20 14:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab_management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminonDuty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        help_text="อีเมลติดต่อ (เช่น admin@example.com)",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "admin_on_duty",
                    models.CharField(
                        blank=True,
                        help_text="เจ้าหน้าที่ดูแลระบบประจำวัน",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, help_text="เบอร์โทรศัพท์ติดต่อ", max_length=50, null=True
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="computer",
            name="current_user",
        ),
        migrations.RemoveField(
            model_name="computer",
            name="installed_software",
        ),
        migrations.RemoveField(
            model_name="computer",
            name="pc_id",
        ),
        migrations.RemoveField(
            model_name="computer",
            name="pc_type",
        ),
        migrations.RemoveField(
            model_name="computer",
            name="session_start",
        ),
        migrations.RemoveField(
            model_name="software",
            name="software_type",
        ),
        migrations.AddField(
            model_name="computer",
            name="Software",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lab_management.software",
                verbose_name="ซอฟต์แวร์ที่ติดตั้ง",
            ),
        ),
        migrations.AddField(
            model_name="computer",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="รายละเอียดเพิ่มเติม"
            ),
        ),
        migrations.AddField(
            model_name="computer",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, verbose_name="อัปเดตสถานะล่าสุด"),
        ),
        migrations.AddField(
            model_name="software",
            name="expire_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="วันหมดอายุ License"
            ),
        ),
        migrations.AddField(
            model_name="software",
            name="type",
            field=models.CharField(
                choices=[
                    ("Software", "Software (ทั่วไป)"),
                    ("AI", "AI Tool (ปัญญาประดิษฐ์)"),
                ],
                default="Software",
                max_length=20,
                verbose_name="ประเภท",
            ),
        ),
        migrations.AddField(
            model_name="usagelog",
            name="Software",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="usagelog",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usagelog",
            name="department",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="usagelog",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("staff", "Staff"),
                    ("guest", "Guest"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="usagelog",
            name="user_year",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="computer",
            name="name",
            field=models.CharField(max_length=20, unique=True, verbose_name="ชื่อเครื่อง"),
        ),
        migrations.AlterField(
            model_name="computer",
            name="status",
            field=models.CharField(
                choices=[
                    ("AVAILABLE", "ว่าง (AVAILABLE)"),
                    ("IN_USE", "ใช้งาน (IN USE)"),
                    ("RESERVED", "จองแล้ว (RESERVED)"),
                    ("MAINTENANCE", "แจ้งซ่อม (MAINT.)"),
                ],
                default="AVAILABLE",
                max_length=20,
                verbose_name="สถานะปัจจุบัน",
            ),
        ),
        migrations.AlterField(
            model_name="software",
            name="name",
            field=models.CharField(max_length=100, verbose_name="ชื่อรายการ"),
        ),
        migrations.AlterField(
            model_name="software",
            name="version",
            field=models.CharField(max_length=50, verbose_name="แพ็กเกจ (Package)"),
        ),
        migrations.AlterField(
            model_name="usagelog",
            name="computer",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="usagelog",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="usagelog",
            name="start_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_id",
                    models.CharField(max_length=20, verbose_name="รหัสนักศึกษา"),
                ),
                ("start_time", models.DateTimeField(verbose_name="เวลาเริ่มใช้งาน")),
                ("end_time", models.DateTimeField(verbose_name="เวลาสิ้นสุดการใช้งาน")),
                (
                    "booking_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="วันที่ทำการจอง"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "รออนุมัติ"),
                            ("APPROVED", "อนุมัติแล้ว"),
                            ("REJECTED", "ไม่อนุมัติ/ยกเลิก"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="สถานะการจอง",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="เวลาที่ทำรายการ"
                    ),
                ),
                (
                    "computer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="lab_management.computer",
                        verbose_name="เครื่องคอมพิวเตอร์",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SiteConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lab_name",
                    models.CharField(
                        default="CKLab",
                        help_text="ชื่อห้องปฏิบัติการที่จะแสดงบนเว็บไซต์",
                        max_length=255,
                    ),
                ),
                (
                    "booking_enabled",
                    models.BooleanField(
                        default=True, help_text="เปิด/ปิด การใช้งานระบบจอง"
                    ),
                ),
                (
                    "announcement",
                    models.TextField(
                        blank=True,
                        help_text="ข้อความประกาศ (แสดงบนหน้า Kiosk)",
                        null=True,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="สถานที่ตั้ง (เช่น อาคาร 4 ชั้น 2)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "is_open",
                    models.BooleanField(
                        default=True, help_text="สถานะการให้บริการห้องแล็บ (เปิด/ปิด)"
                    ),
                ),
                (
                    "admin_on_duty",
                    models.ForeignKey(
                        blank=True,
                        help_text="เจ้าหน้าที่ดูแลระบบประจำวัน",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="lab_management.adminonduty",
                    ),
                ),
            ],
        ),
    ]
