# Generated by Django 6.0.2 on 2026-02-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='feedback_url',
            field=models.CharField(blank=True, default='https://docs.google.com/forms/d/e/1FAIpQLSfnaw6G3NFsuKwngOenWfQ2pU3AQDAYbJ-ON1W5TpU8xjDeKw/viewform?embedded=true', help_text='ลิงก์แบบประเมิน (Google Form)', max_length=500, null=True),
        ),
    ]
