# Generated by Django 6.0.2 on 2026-03-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_management', '0002_siteconfig_feedback_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ชื่อผู้จอง'),
        ),
    ]
